version: "3"

services:
  prisma-mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: LdsfgjpmLDSFg8941sdfgsdfc
      MYSQL_DATABASE: mysql_database
    ports:
      - "3306:3306"
    volumes:
      - prisma-mysql-data:/var/lib/mysql

  prisma-redis:
    image: redis:latest

    ports:
      - "6379:6379"
    volumes:
      - prisma-redis-data:/data

  app:
    image: myimage:latest
    environment:
      MYSQL_ROOT_PASSWORD: LdsfgjpmLDSFg8941sdfgsdfc

    env_file:
      - .env
    ports:
      - "3000:3000"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5
    depends_on:
      - prisma-mysql
      - prisma-redis

volumes:
  prisma-mysql-data:
  prisma-redis-data:
